config/routes.rb
Bartapper::Application.routes.draw do
  resources :master_events

  resources :participants

  resources :venues

  resources :teams

  resources :games

	root :to => "games#index"
	

end

app/models/participant.rb
class Participant < ActiveRecord::Base

	belongs_to :master_event
	belongs_to :team
	
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.xml
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.xml
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.xml
  def new
    @participant = Participant.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
  end

  # POST /participants
  # POST /participants.xml
  def create
    @participant = Participant.new(params[:participant])

	#if !params[:master_event_id].blank? && !params[:team_id].blank?
	#@participant.master_event_id = MasterEvent.find_by_id(params[:master_event_id])
	#@participant.team_id = Team.find_by_id(params[:team_id])
	#end
	
    respond_to do |format|
      if @participant.save
        format.html { redirect_to(@participant, :notice => 'Participant was successfully created.') }
        format.xml  { render :xml => @participant, :status => :created, :location => @participant }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @participant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.xml
  def update
    @participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to(@participant, :notice => 'Participant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @participant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.xml
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to(participants_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :master_event_id %><br />
    <%= f.text_field :master_event_id %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br />
    <%= f.text_field :team_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<table>
  <tr>
    <th>Master event</th>
    <th>Team</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @participants.each do |participant| %>
  <tr>
    <td><%= participant.master_event_id %></td>
    <td><%= participant.team_id %></td>
    <td><%= link_to 'Show', participant %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Master event:</b>
  <%= @participant.master_event_id %>
</p>

<p>
  <b>Team:</b>
  <%= @participant.team_id %>
</p>


<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>