config/routes.rb
Bartapper::Application.routes.draw do
  resources :master_events

  resources :participants

  resources :venues

  resources :teams

  resources :games

	root :to => "games#index"
	

end

app/models/master_event.rb
class MasterEvent < ActiveRecord::Base

	# multiple teams playing in the game
	has_many :participants
	# participant mapping to the teams
	has_many :teams, :through => :participants
	# games are the sub-events
	has_many :games
	has_many :venues, :through => :games
	
end

app/controllers/master_events_controller.rb
class MasterEventsController < ApplicationController
  # GET /master_events
  # GET /master_events.xml
  def index
    @master_events = MasterEvent.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @master_events }
    end
  end

  # GET /master_events/1
  # GET /master_events/1.xml
  def show
    @master_event = MasterEvent.find(params[:id])

	@teams = Team.all

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @master_event }
    end
  end

  # GET /master_events/new
  # GET /master_events/new.xml
  def new
    @master_event = MasterEvent.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @master_event }
    end
  end

  # GET /master_events/1/edit
  def edit
    @master_event = MasterEvent.find(params[:id])
  end

  # POST /master_events
  # POST /master_events.xml
  def create
    @master_event = MasterEvent.new(params[:master_event])

    respond_to do |format|
      if @master_event.save
        format.html { redirect_to(@master_event, :notice => 'Master event was successfully created.') }
        format.xml  { render :xml => @master_event, :status => :created, :location => @master_event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @master_event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /master_events/1
  # PUT /master_events/1.xml
  def update
    @master_event = MasterEvent.find(params[:id])

    respond_to do |format|
      if @master_event.update_attributes(params[:master_event])
        format.html { redirect_to(@master_event, :notice => 'Master event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @master_event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /master_events/1
  # DELETE /master_events/1.xml
  def destroy
    @master_event = MasterEvent.find(params[:id])
    @master_event.destroy

    respond_to do |format|
      format.html { redirect_to(master_events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/master_events_helper.rb
module MasterEventsHelper
end

app/views/master_events/_form.html.erb
<%= form_for(@master_event) do |f| %>
  <% if @master_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@master_event.errors.count, "error") %> prohibited this master_event from being saved:</h2>

      <ul>
      <% @master_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  	<%= f.label :title %><br />
  	<%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :time %><br />
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :sport_id %><br />
    <%= f.text_field :sport_id %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/master_events/_teamselect.html.erb
<% for team in @teams %>
<option value="<%= team.id %>"><%= team.name %></option>
<% end %>

app/views/master_events/edit.html.erb
<h1>Editing master_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @master_event %> |
<%= link_to 'Back', master_events_path %>

app/views/master_events/index.html.erb
<h3>Master Event Manager</h3>

<table>
  <tr>
    <th>Time</th>
    <th>Date</th>
    <th>Sport</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @master_events.each do |master_event| %>
  <tr>
  	<td><%= master_event.title %></td>
    <td><%= master_event.time %></td>
    <td><%= master_event.date %></td>
    <td><%= master_event.sport_id %></td>
    <td><%= master_event.description %></td>
    <td><%= link_to 'Show', master_event %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Master event', new_master_event_path %>

app/views/master_events/new.html.erb
<h2>Add Master Event</h2>

<%= render 'form' %>

<%= link_to 'Back', master_events_path %>

app/views/master_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Time:</b>
  <%= @master_event.time %>
</p>

<p>
  <b>Date:</b>
  <%= @master_event.date %>
</p>

<p>
  <b>Sport:</b>
  <%= @master_event.sport_id %>
</p>

<p>
  <b>Description:</b>
  <%= @master_event.description %>
</p>

<b>ADMIN TOOLS</b><br /><br />
<!-- add teams to the event with form -->
<b> Add Teams to this Event: </b>
<%= form_tag(:controller => 'participants', :action => 'create') do %>
<%= select("participant","team_id", Team.all.collect {|t| [t.name, t.id]}) %>
<%= hidden_field_tag 'participant[master_event_id])', @master_event.id %>
<%= submit_tag 'Submit' %>
<% end %>
<br />

<br />
<br />

<%= link_to 'Edit', edit_master_event_path(@master_event) %> |
<%= link_to 'Back', master_events_path %>