config/routes.rb
Bartapper::Application.routes.draw do
  resources :master_events

  resources :participants

  resources :venues

  resources :teams

  resources :games

	root :to => "games#index"
	

end

app/models/game.rb
class Game < ActiveRecord::Base

	belongs_to :master_event
	belongs_to :venue
	
	def as_json(options={})
		super(:include => [:venue, :master_event])
	end
	
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.xml
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @games }
      format.json { render :json => @games }
    end
  end

  # GET /games/1
  # GET /games/1.xml
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @game }
    end
  end

  # GET /games/new
  # GET /games/new.xml
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.xml
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to(@game, :notice => 'Game was successfully created.') }
        format.xml  { render :xml => @game, :status => :created, :location => @game }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.xml
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to(@game, :notice => 'Game was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.xml
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to(games_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :venue_id %><br />
    <%= f.text_field :venue_id %>
  </div>
  <div class="field">
    <%= f.label :sport_id %><br />
    <%= f.text_field :sport_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false">
</script>

<h3>Games Playing Nearby</h3>

<div id="map_canvas" style="width:870px; height:40em; margin-bottom:1em;">
</div>

<table>
  <tr>
    <th>Date</th>
    <th>Time</th>
    <th>Venue</th>
    <th>Sport</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<h3>Details</h3>
<% @games.each do |game| %>
  <tr>
    <td><%= game.date %></td>
    <td><%= game.time %></td>
    <td><%= game.venue_id %></td>
    <td><%= game.sport_id %></td>
    <td><%= game.title %></td>
    <td><%= game.description %></td>
    <td><%= link_to 'Show', game %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @game.date %>
</p>

<p>
  <b>Time:</b>
  <%= @game.time %>
</p>

<p>
  <b>Venue:</b>
  <%= @game.venue_id %>
</p>

<p>
  <b>Sport:</b>
  <%= @game.sport_id %>
</p>

<p>
  <b>Title:</b>
  <%= @game.title %>
</p>

<p>
  <b>Description:</b>
  <%= @game.description %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>