config/routes.rb
Bartapper::Application.routes.draw do
  resources :master_events

  resources :participants

  resources :venues

  resources :teams

  resources :games

	root :to => "games#index"
	

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pubtapper</title>
  <%= csrf_meta_tag %>
  	<!-- JQUERY -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" type="text/javascript"></script>
	<!-- END JQUERY -->
	<!-- JQUERY UI -->
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js" type="text/javascript"></script>
	<!-- END JQUERY UI -->
  	<!-- BLUEPRINT -->
	<link rel="stylesheet" href="/stylesheets/blueprint/screen.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="/stylesheets/blueprint/print.css" type="text/css" media="print">
	<!--[if lt IE 8]>
	<link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection">
	<![endif]-->
	<!-- END BLUEPRINT -->
  	<%= stylesheet_link_tag "scaffold" %>
	<%= stylesheet_link_tag "main" %>
	<script type="text/javascript" src="http://use.typekit.com/etq6pwf.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  	<%= javascript_include_tag 'application' %>
  	<!-- google analytics -->
  	<script type="text/javascript">	
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-23524014-2']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	
	</script>
</head>
<body>
<div class="prepend-1" id="container">
	<div>
		<div class="prepend-1 span-23 last" id="mainbox">
			<!-- logo section -->
			<div class="span-22" last">
				<div class="logo" class="tk-octin-sports"><%= link_to "PubTapper", root_path %></div>
			<h2 style="margin-bottom:1em;">Games on Tap.</h2>
			</div>
			<div class="span-22" last" id="menubar" style="margin-bottom:2em;">
			<%= link_to "GAMES", games_path %>
			<%= link_to "THE FEED" %>
			<%= link_to "TEAMS", teams_path %>
			<%= link_to "VENUES", venues_path %>
			<%= link_to "ADMIN", master_events_path %>
			</div>
		
			<%= yield %>
		</div>
	</div>
</div>
</body>
</html>